### ISSUE TITLE
pcl_ros build error  -  Errors     << pcl_ros:make /home/username/perception_ws/logs/pcl_ros/build.make.002.log                                       

### ISSUE THREAD

**Issue by BhooshanDeshpande** [ethz-asl/depth_segmentation#55]
```
Warnings   << pcl_ros:check /home/bhooshan/perception_ws/logs/pcl_ros/build.check.001.log                                     
CMake Warning (dev) at CMakeLists.txt:2 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    CMAKE_PROJECT_VERSION
    CMAKE_PROJECT_VERSION_MAJOR
    CMAKE_PROJECT_VERSION_MINOR
    CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at /home/bhooshan/perception_ws/devel/share/pcl_catkin/cmake/pcl-extras.cmake:14 (find_package):
  By not providing "FindQVTK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "QVTK", but
  CMake did not find one.

  Could not find a package configuration file provided by "QVTK" with any of
  the following names:

    QVTKConfig.cmake
    qvtk-config.cmake

  Add the installation prefix of "QVTK" to CMAKE_PREFIX_PATH or set
  "QVTK_DIR" to a directory containing one of the above files.  If "QVTK"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /home/bhooshan/perception_ws/devel/share/pcl_catkin/cmake/pcl_catkinConfig.cmake:222 (include)
  CMakeLists.txt:10 (find_package)


cd /home/bhooshan/perception_ws/build/pcl_ros; catkin build --get-env pcl_ros | catkin env -si  /usr/bin/make cmake_check_build_system; cd -

..............................................................................................................................
______________________________________________________________________________________________________________________________
Errors     << pcl_ros:make /home/bhooshan/perception_ws/logs/pcl_ros/build.make.002.log                                       
make[2]: Circular /home/bhooshan/perception_ws/devel/lib/libpcl_ros_filter.so <- /home/bhooshan/perception_ws/devel/lib/libpcl_ros_filter.so dependency dropped.
make[2]: Circular /home/bhooshan/perception_ws/devel/lib/libpcl_ros_filter.so <- /home/bhooshan/perception_ws/devel/lib/libpcl_ros_filter.so dependency dropped.
c++: fatal error: input file ‘/home/bhooshan/perception_ws/devel/lib/libpcl_ros_filter.so’ is the same as output file
compilation terminated.
make[2]: *** [CMakeFiles/pcl_ros_filter.dir/build.make:500: /home/bhooshan/perception_ws/devel/lib/libpcl_ros_filter.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:525: CMakeFiles/pcl_ros_filter.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: /opt/ros/noetic/lib/libtf.so: undefined reference to `tf2_ros::TransformListener::TransformListener(tf2::BufferCore&, ros::NodeHandle const&, bool, ros::TransportHints)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/bag_to_pcd.dir/build.make:500: /home/bhooshan/perception_ws/devel/lib/pcl_ros/bag_to_pcd] Error 1
make[1]: *** [CMakeFiles/Makefile2:2114: CMakeFiles/bag_to_pcd.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
cd /home/bhooshan/perception_ws/build/pcl_ros; catkin build --get-env pcl_ros | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

..............................................................................................................................

```

I am getting this error despite there have been some discussions about this specific errors  6 years ago. I do not think that it is wise to pursue the resolutions discussed then, and some of the involved packages are outdated too. my system is Ubuntu 20.04 - ROS noetic . The error has to do with pcl_ros dependencies as mentioned in the CMakeLists.txt. If anyone has encountered this, please let me know a work around.

**Comment by jmwang0117** [comment]
> ```
> Warnings   << pcl_ros:check /home/bhooshan/perception_ws/logs/pcl_ros/build.check.001.log                                     
> CMake Warning (dev) at CMakeLists.txt:2 (project):
>   Policy CMP0048 is not set: project() command manages VERSION variables.
>   Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
>   command to set the policy and suppress this warning.
> 
>   The following variable(s) would be set to empty:
> 
>     CMAKE_PROJECT_VERSION
>     CMAKE_PROJECT_VERSION_MAJOR
>     CMAKE_PROJECT_VERSION_MINOR
>     CMAKE_PROJECT_VERSION_PATCH
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning at /home/bhooshan/perception_ws/devel/share/pcl_catkin/cmake/pcl-extras.cmake:14 (find_package):
>   By not providing "FindQVTK.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "QVTK", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "QVTK" with any of
>   the following names:
> 
>     QVTKConfig.cmake
>     qvtk-config.cmake
> 
>   Add the installation prefix of "QVTK" to CMAKE_PREFIX_PATH or set
>   "QVTK_DIR" to a directory containing one of the above files.  If "QVTK"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> Call Stack (most recent call first):
>   /home/bhooshan/perception_ws/devel/share/pcl_catkin/cmake/pcl_catkinConfig.cmake:222 (include)
>   CMakeLists.txt:10 (find_package)
> 
> 
> cd /home/bhooshan/perception_ws/build/pcl_ros; catkin build --get-env pcl_ros | catkin env -si  /usr/bin/make cmake_check_build_system; cd -
> 
> ..............................................................................................................................
> ______________________________________________________________________________________________________________________________
> Errors     << pcl_ros:make /home/bhooshan/perception_ws/logs/pcl_ros/build.make.002.log                                       
> make[2]: Circular /home/bhooshan/perception_ws/devel/lib/libpcl_ros_filter.so <- /home/bhooshan/perception_ws/devel/lib/libpcl_ros_filter.so dependency dropped.
> make[2]: Circular /home/bhooshan/perception_ws/devel/lib/libpcl_ros_filter.so <- /home/bhooshan/perception_ws/devel/lib/libpcl_ros_filter.so dependency dropped.
> c++: fatal error: input file ‘/home/bhooshan/perception_ws/devel/lib/libpcl_ros_filter.so’ is the same as output file
> compilation terminated.
> make[2]: *** [CMakeFiles/pcl_ros_filter.dir/build.make:500: /home/bhooshan/perception_ws/devel/lib/libpcl_ros_filter.so] Error 1
> make[1]: *** [CMakeFiles/Makefile2:525: CMakeFiles/pcl_ros_filter.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> /usr/bin/ld: /opt/ros/noetic/lib/libtf.so: undefined reference to `tf2_ros::TransformListener::TransformListener(tf2::BufferCore&, ros::NodeHandle const&, bool, ros::TransportHints)'
> collect2: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/bag_to_pcd.dir/build.make:500: /home/bhooshan/perception_ws/devel/lib/pcl_ros/bag_to_pcd] Error 1
> make[1]: *** [CMakeFiles/Makefile2:2114: CMakeFiles/bag_to_pcd.dir/all] Error 2
> make: *** [Makefile:141: all] Error 2
> cd /home/bhooshan/perception_ws/build/pcl_ros; catkin build --get-env pcl_ros | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -
> 
> ..............................................................................................................................
> ```
> 
> 尽管 6 年前就这个特定错误进行了一些讨论，但我还是收到了这个错误。我不认为追求当时讨论的决议是明智的，而且一些涉及的软件包也已经过时了。我的系统是 Ubuntu 20.04 - ROS noetic 。该错误与 CMakeLists.txt 中提到的 pcl_ros 依赖项有关。如果有人遇到过这种情况，请让我知道解决方法。

Hello, I also encountered this problem, did you solve this problem? Can you let me know? Thanks!
